### ISSUE TITLE
GA analytics

### ISSUE THREAD

**Issue by fmmattioni** [chachabooms/dmtools#19]
Hi @chachabooms! Thank you for checking the {whippr} package. I also see that your {dmtools} package is quite interesting! I have noticed that you associated my GA analytics id here in your pkgdown file: 

https://github.com/chachabooms/dmtools/blob/master/_pkgdown.yml#L6

Would you mind correcting it?

Thank you in advance!
Felipe

**Comment by chachabooms** [comment]
Oh sure. This is because I took your pkgdown file as a basis. Excuse me

**Comment by fmmattioni** [comment]
No problem 👍

**Comment by chachabooms** [comment]
Done
